// actions Authentication

export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const GET_USER_DATA = "GET_USER_DATA";
export const SIGN_OUT = "SIGN_OUT";
//export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
//export const LOGIN_REGISTRATION = "LOGIN_REGISTRATION";
//export const LOGIN_ERROR = "LOGIN_ERROR";
